### ISSUE TITLE
Visuel épuré

### ISSUE THREAD

**Issue by loicsikidi** [suricats/emotions_vocales#7]
Scénario

1. On arrive sur la page d'accueil
2. On active un des options (librairie, enregistrement, etc.)
3. On supprime qu'un component (croix rouge)
4. On obtient un écran épuré avec seulement les icônes (cf. imprim écran ci-dessous)
<img width="1280" alt="Capture d’écran 2019-07-02 à 00 21 09" src="https://user-images.githubusercontent.com/11026721/60470150-b42a2d80-9c5f-11e9-9c21-3b6a3a8011c1.png">

Est-ce normal ?

**Comment by LucileDesfour** [comment]
Je pense que je peux rajouter un label avec "Choisissez une des options ci-dessus"
