### ISSUE TITLE
Les components s'accumulent sans fin

### ISSUE THREAD

**Issue by loicsikidi** [suricats/emotions_vocales#8]
**Comportement observé**: si on switch entre les différentes options (enregistrement, lib, etc.) sans fermer les components, ils s'accumulent. Tant et si bien, que l'on se retrouve avec une page qui croule sous les components.

<img width="1280" alt="Capture d’écran 2019-07-02 à 00 32 38" src="https://user-images.githubusercontent.com/11026721/60470500-ea1be180-9c60-11e9-98b7-900c9a7870a5.png">

Est-ce le comportement attendu ?

**Comment by LucileDesfour** [comment]
Je pense que c'est mieux de ne pas supprimer les enregistements des utilisateurs si ils ne l'ont pas demandé.
